services:
  eventdrivenwebapplication.api:
    image: ${DOCKER_REGISTRY-}eventdrivenwebapplicationapi
    build:
      context: ..\
      dockerfile: docker\eventdrivenwebapplication.api\Dockerfile
    container_name: eventdrivenwebapplication.api
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - sqlserver
      - rabbitmq
      - nifi
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://0.0.0.0:8080;https://0.0.0.0:8081
      ASPNETCORE_HTTPS_PORT: 8081
    restart: unless-stopped
    
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStr0ngP@ssw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8082:8080"
    networks:
      - app-network
    environment:
      NIFI_WEB_HTTP_PORT: 8080
      NIFI_WEB_PROXY_HOST: localhost
      NIFI_WEB_PROXY_PORT: 8082
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
