namespace EventDrivenWebApplication.Domain.Entities;
public class InventoryItem
{
    public int Id { get; set; }            // Autogenerated primary key
    public Guid ProductId { get; set; }    // Business identifier
    public string Name { get; set; }       // Product name
    public int Quantity { get; set; }      // Current stock quantity
    public bool IsChecked { get; set; }    // Inventory check status
    public DateTime? LastCheckedAt { get; set; } // Optional last checked timestamp
}
